### PR TITLE
Cocoapods support.

### PR DESCRIPTION
**Pull request by rokgregoric**

### CODE REVIEW

**Comment by LukasCZ** [comment]
Hi,
thanks for the pull request and for the effort, but the way you load retina images seems wrong, so I am not very keen on merging it. But if you created just the one with the podspec, that would be great, and I would merge it.

**Comment by rokgregoric** [comment]
Yes, agreed ... but that's a workaround to be able to load the assets when using inside a project or loaded as a framework, which requires special treatment. That's the only way I found to work for both. I will add a comment to make that clear.

**Comment by rokgregoric** [comment]
OK done .. I've also added a way to override the assets embedded in the framework with assets from the local project.

**Comment by d0n13** [comment]
Can this be merged to master?

**Comment by LukasCZ** [comment]
I've now added CocoaPods support (I'm sorry I didn't use your code, but I wanted to do it myself.) I've never had a PR on one of my repositories before so I'm quite new to this.

As for the solution - I'm not sure if it will work when imported as !use_frameworks, but I think it should.

**Pull request closed without merging**
